import { ProfileDefinition } from '../types';

export const BASE_PROFILE_DEFINITIONS: ProfileDefinition[] = [
  {
    id: 'public-service',
    label: 'Public Service',
    summaryStyle: 'Mission-focused, dependable, civic impact oriented, and grounded in service delivery.',
    skillsOrdering: ['Leadership', 'Backend', 'Platforms', 'Cloud', 'Compliance'],
    preferredDomainTags: ['public-sector', 'government', 'service-delivery', 'community'],
    preferredBulletTags: ['leadership', 'reliability', 'operations', 'compliance', 'incident-response'],
    disfavoredBulletTags: ['speculative', 'trading', 'crypto-only'],
    typicalExperienceInclusionDefaults: ['focus-public-sector', 'focus-leadership'],
    toneGuidance: 'Direct, service-oriented, calm, and outcomes focused.',
    recommendedDefaultExperienceBlocks: [],
    hiddenIfUnsupported: false,
  },
  {
    id: 'backend-engineer',
    label: 'Backend Engineer',
    summaryStyle: 'Systems-focused backend engineer with emphasis on APIs, integrations, reliability, and delivery.',
    skillsOrdering: ['Backend', 'APIs', 'Cloud', 'Data', 'Tooling'],
    preferredDomainTags: ['backend', 'enterprise-platform', 'integration', 'distributed-systems'],
    preferredBulletTags: ['backend', 'api', 'integration', 'performance', 'reliability'],
    disfavoredBulletTags: ['front-end-only', 'design-only'],
    typicalExperienceInclusionDefaults: ['focus-backend'],
    toneGuidance: 'Concise, implementation oriented, and technically specific.',
    recommendedDefaultExperienceBlocks: [],
    hiddenIfUnsupported: false,
  },
  {
    id: 'general-swe',
    label: 'General Software Engineer',
    summaryStyle: 'Balanced software engineering framing spanning product delivery, technical breadth, and collaboration.',
    skillsOrdering: ['Languages', 'Platforms', 'Backend', 'Frontend', 'Cloud'],
    preferredDomainTags: ['software-engineering', 'backend', 'platform', 'delivery'],
    preferredBulletTags: ['delivery', 'ownership', 'collaboration', 'architecture'],
    disfavoredBulletTags: ['hyper-specialized'],
    typicalExperienceInclusionDefaults: ['focus-backend', 'focus-leadership'],
    toneGuidance: 'Broadly credible, measured, and adaptable.',
    recommendedDefaultExperienceBlocks: [],
    hiddenIfUnsupported: false,
  },
  {
    id: 'blockchain-engineer',
    label: 'Blockchain Engineer',
    summaryStyle: 'Enterprise blockchain and distributed systems framing without overstating unsupported expertise.',
    skillsOrdering: ['Distributed Systems', 'Backend', 'APIs', 'Cloud', 'Security'],
    preferredDomainTags: ['blockchain', 'distributed-systems', 'enterprise-platform', 'integration'],
    preferredBulletTags: ['blockchain', 'interoperability', 'backend', 'api'],
    disfavoredBulletTags: ['consumer-marketing'],
    typicalExperienceInclusionDefaults: ['focus-blockchain', 'focus-backend'],
    toneGuidance: 'Specific, technically grounded, and conservative about domain claims.',
    recommendedDefaultExperienceBlocks: [],
    hiddenIfUnsupported: true,
  },
];
