export const LLM_CLIENT = Symbol('LLM_CLIENT');
export const RESUME_EXTRACTION_PROVIDER = Symbol('RESUME_EXTRACTION_PROVIDER');
export const RESUME_MERGE_PROVIDER = Symbol('RESUME_MERGE_PROVIDER');
export const JOB_ANALYSIS_PROVIDER = Symbol('JOB_ANALYSIS_PROVIDER');
export const RESUME_REWRITE_PROVIDER = Symbol('RESUME_REWRITE_PROVIDER');
export const REPORT_GENERATION_PROVIDER = Symbol('REPORT_GENERATION_PROVIDER');
